# Generated by Django 5.0.4 on 2024-05-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_residuos')),
                ('descricao', models.TextField(max_length=10000)),
                ('categoria', models.CharField(choices=[('GRANDES_EQUIPAMENTOS', 'Grandes Equipamentos'), ('PEQUENOS_EQUIPAMENTOS/ELETROPORTATEIS', 'Pequenos Equipamentos ou Eletroportáteis'), ('EQUIPAMENTOS_INFORMATICA/TELEFONIA', 'Equipamentos de Informática ou Telefonia'), ('PILHAS/BATERIAS', 'Pilhas ou Baterias portáteis')], max_length=50)),
            ],
        ),
    ]
